
package ru.company.services.web.api;

import ru.company.services.personws.Person;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://personws.services.company.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @param id
     */
    @WebMethod
    @Action(input = "http://personws.services.company.ru/PersonService/deleteRequest", output = "http://personws.services.company.ru/PersonService/deleteResponse")
    public void delete(
        @WebParam(name = "id", partName = "id")
        long id);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://personws.services.company.ru/PersonService/createRequest", output = "http://personws.services.company.ru/PersonService/createResponse")
    public void create(
        @WebParam(name = "arg0", partName = "arg0")
                Person arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://personws.services.company.ru/PersonService/modifyRequest", output = "http://personws.services.company.ru/PersonService/modifyResponse")
    public void modify(
        @WebParam(name = "arg0", partName = "arg0")
        Person arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.company.services.personws.PersonList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://personws.services.company.ru/PersonService/getListRequest", output = "http://personws.services.company.ru/PersonService/getListResponse")
    public PersonList getList(
        @WebParam(name = "arg0", partName = "arg0")
        Person arg0);

}
