
package ru.company.services.personws;

import ru.company.ConfigUtils;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthServiceImplService", targetNamespace = "http://personws.services.company.ru/")
public class AuthServiceImplService
    extends Service
{

    private final static URL AUTHSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName AUTHSERVICEIMPLSERVICE_QNAME = new QName("http://personws.services.company.ru/", "AuthServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(ConfigUtils.getHostUrl()+ "/personws/auth?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        AUTHSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AuthServiceImplService() {
        super(__getWsdlLocation(), AUTHSERVICEIMPLSERVICE_QNAME);
    }

    public AuthServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHSERVICEIMPLSERVICE_QNAME, features);
    }

    public AuthServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, AUTHSERVICEIMPLSERVICE_QNAME);
    }

    public AuthServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHSERVICEIMPLSERVICE_QNAME, features);
    }

    public AuthServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthServiceImpl
     */
    @WebEndpoint(name = "AuthServiceImplPort")
    public AuthServiceImpl getAuthServiceImplPort() {
        return super.getPort(new QName("http://personws.services.company.ru/", "AuthServiceImplPort"), AuthServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthServiceImpl
     */
    @WebEndpoint(name = "AuthServiceImplPort")
    public AuthServiceImpl getAuthServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://personws.services.company.ru/", "AuthServiceImplPort"), AuthServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw AUTHSERVICEIMPLSERVICE_EXCEPTION;
        }
        return AUTHSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
