
package ru.company.services.personws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthServiceImpl", targetNamespace = "http://personws.services.company.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthServiceImpl {


    /**
     * 
     * @param authRequest
     * @return
     *     returns ru.company.services.personws.TAuthResponse
     */
    @WebMethod
    @WebResult(name = "authResponse", targetNamespace = "")
    @RequestWrapper(localName = "auth", targetNamespace = "http://personws.services.company.ru/", className = "ru.company.services.personws.Auth")
    @ResponseWrapper(localName = "authResponse", targetNamespace = "http://personws.services.company.ru/", className = "ru.company.services.personws.AuthResponse")
    @Action(input = "http://personws.services.company.ru/AuthServiceImpl/authRequest", output = "http://personws.services.company.ru/AuthServiceImpl/authResponse")
    public TAuthResponse auth(
        @WebParam(name = "authRequest", targetNamespace = "")
        TAuthRequest authRequest);

}
